version: 0.2

phases:
  build:
    commands:
      - echo "BUILDING"
  post_build:
    commands:
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo "Build PASS"; else echo "Build FAIL"; exit 1; fi
      - dotnet publish MoonCar/MoonCar.csproj -c Release -o output
artifacts:
  files:
    - '/output'