version: 0.2

phases:
  build:
    commands:
      - echo "Test"
      - dotnet publish MoonCarTest/MoonCarTest.csproj -c Release -o MoonCarTestOutput
      - cd MoonCarTestOutput && dotnet vstest MoonCarTest.dll
  post_build:
    commands:
      - echo "Build"
      - if [ $CODEBUILD_BUILD_SUCCEEDING = 1 ]; then echo "Build PASS"; else echo "Build FAIL"; exit 1; fi
      - dotnet publish MoonCar/MoonCar.csproj -c Release -o output
artifacts:
  files:
    - 'output/*'